version: '3'

services:
  akhiranode0:
    image: AkhiraChain/akhiranode:latest
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET0}
      MONIKER: akhiranode0
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR0}
    volumes:
      - ./sifnode/root/scripts:/root/scripts:Z
    command: /root/scripts/akhiranode.sh
    networks:
      sifchain:
        ipv4_address: ${IPADDR0}

  akhiranode1:
    image: AkhiraChain/akhiranode:latest
    ports:
      - 2317:1317
      - 36656:26656
      - 36657:26657
    environment:
      CHAINNET: ${CHAINNET1}
      MONIKER: akhiranode1
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR1}
    volumes:
      - ./akhira/root/scripts:/root/scripts:Z
    command: /root/scripts/akhiranode.sh
    networks:
      akhirachain:
        ipv4_address: ${IPADDR1}

  ts-relayer:
    image: akhirachain/ts-relayer:latest
    environment:
      CHAINNET0: ${CHAINNET0}
      CHAINNET1: ${CHAINNET1}
      RELAYER_SRC: ${CHAINNET0}
      RELAYER_DEST: ${CHAINNET1}
      AKHIRANODE0_MNEMONIC: ${MNEMONIC}
      AKHIRANODE1_MNEMONIC: ${MNEMONIC}
      RPC0: ${IPADDR0}:26657
      RPC1: ${IPADDR1}:26657
      PREFIX0: ak
      PREFIX1: ak
      GAS_PRICE0: "0.5aku"
      GAS_PRICE1: "0.5aku"
    volumes:
      - ./ts-relayer/root/scripts:/root/scripts:Z
    depends_on:
      - akhiranode0
      - akhiranode1
    command: /root/scripts/ts-relayer.sh
    networks:
      akhirachain:
        ipv4_address: ${IPADDR2}

networks:
  akhirachain:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
