name: akhiradocker Image Build and Publish

on:
  workflow_dispatch:
env:
  IMAGE_NAME: akhiradocker

jobs:
  build_akhiradocker:
    runs-on: ubuntu-latest
    permissions: 
       packages: write
       pull-requests: write       
    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: cd test/integration; docker build -t ghcr.io/AkhiraChain/akhiranode/$IMAGE_NAME:latest -f Dockerfile.devenv .

    - name: Log into registry
      run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: docker push ghcr.io/AkhiraChain/akhiranode/$IMAGE_NAME:latest

      